[package]
name = "entropy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
chrono = "0.4.35"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde-pickle = "1.1.1"
serde_bytes = "0.11.14"
serde_json = "1.0.114"
serde_with = { version = "3.7.0", features = ["hex"] }
