[package]
name = "entropy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.11", features = ["serde"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
dbgprint = "0.1.0"
moka = { version = "0.12.5", features = ["sync"] }
ordered-float = { version = "4.2.0", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde-pickle = "1.1.1"
serde_bytes = "0.11.14"
serde_json = "1.0.114"
sled = { version = "0.34.7" }
thiserror = "1.0.58"
typed-sled = "0.2.3"

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
