[package]
name = "entropy"
version = "0.1.0"
edition = "2021"
description = "A game serve as RESTful"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.11", features = ["serde"] }
anyhow = "1.0.82"
async-trait = "0.1.80"
axum = { version = "0.7.5", features = ["query", "macros"] }
axum-login = "0.15.1"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
futures = "0.3.30"
nanoid = "0.4.0"
ordered-float = { version = "4.2.0", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive", "alloc"] }
serde-pickle = "1.1.1"
serde_bytes = "0.11.14"
serde_json = "1.0.114"
sled = { version = "0.34.7" }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
typed-sled = "0.2.3"

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
